### ISSUE TITLE
网络问题

### ISSUE THREAD

**Issue by Breeze-J** [xihongyang1999/CCGC#4]
请问，为什么网络只用只有一层隐藏层的MLP，而不是使用其他的图神经网络，使用单层MLP是有什么原因吗？

**Comment by xihongyang1999** [comment]
您好，因为前面的滤波已经将结构信息包含在内，所以后面编码就只使用了MLP，这部分的具体细节可以参考AGE的论文。

**Comment by Breeze-J** [comment]
好的，谢谢回复。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xihongyang1999/CCGC"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年11月30日(星期四) 上午10:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xihongyang1999/CCGC] 网络问题 (Issue #4)





 
您好，因为前面的滤波已经将结构信息包含在内，所以后面编码就只使用了MLP，这部分的具体细节可以参考AGE的论文。
