### ISSUE TITLE
X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？

### ISSUE THREAD

**Issue by TengXYi** [xihongyang1999/CCGC#5]
X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？

**Comment by xihongyang1999** [comment]
您好，是都包含的，滤波的形式已经将结构信息包含在内了。具体细节可以参考AGE。

**Comment by TengXYi** [comment]
你好，X 已经都包含了吗？后面不是进行了邻域信息聚合才包含结构信息吗，再经过平滑操作得到 X～不太明白，望解惑感谢！发自我的手机-------- 原始邮件 --------发件人： Xihong Yang ***@***.***>日期： 2023年11月30日周四 10:07收件人： xihongyang1999/CCGC ***@***.***>抄送： TengXYi ***@***.***>, Author ***@***.***>主    题： Re: [xihongyang1999/CCGC] X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？ (Issue #5)
您好，是都包含的，滤波的形式已经将结构信息包含在内了。具体细节可以参考AGE。

**Comment by xihongyang1999** [comment]
> 你好，X 已经都包含了吗？后面不是进行了邻域信息聚合才包含结构信息吗，再经过平滑操作得到 X～不太明白，望解惑感谢！发自我的手机-------- 原始邮件 --------发件人： Xihong Yang ***@***.***>日期： 2023年11月30日周四 10:07收件人： xihongyang1999/CCGC ***@***.***>抄送： TengXYi ***@***.***>, Author ***@***.***>主 题： Re: [xihongyang1999/CCGC] X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？ (Issue #5) 您好，是都包含的，滤波的形式已经将结构信息包含在内了。具体细节可以参考AGE。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

sorry，刚刚看错了，原始的X是只有特征的，我看成了X~

**Comment by TengXYi** [comment]
谢谢解答🌹发自我的手机-------- 原始邮件 --------发件人： Xihong Yang ***@***.***>日期： 2023年11月30日周四 10:29收件人： xihongyang1999/CCGC ***@***.***>抄送： TengXYi ***@***.***>, Author ***@***.***>主    题： Re: [xihongyang1999/CCGC] X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？ (Issue #5)

你好，X 已经都包含了吗？后面不是进行了邻域信息聚合才包含结构信息吗，再经过平滑操作得到 X～不太明白，望解惑感谢！发自我的手机-------- 原始邮件 --------发件人： Xihong Yang @.>日期： 2023年11月30日周四 10:07收件人： xihongyang1999/CCGC @.>抄送： TengXYi @.>, Author @.>主 题： Re: [xihongyang1999/CCGC] X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？ (Issue #5) 您好，是都包含的，滤波的形式已经将结构信息包含在内了。具体细节可以参考AGE。 —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: @.***>

sorry，刚刚看错了，原始的X是只有特征的，我看成了X~

**Comment by TengXYi** [comment]
我是一名图聚类方向的硕士研究生，我想请问数据集划分的问题，我读了您的很多论文，看了一部分论文的代码，我发现您都是在归纳式学习上进行训练的模型，我最近也在归纳式学习上有所进展，但苦于数据集划分问题，不论是过去的方法亦或者我自己的模型，表现的都不是很好。因此，想向您请教关于您的数据集是如何划分的？发自我的手机-------- 原始邮件 --------发件人： Xihong Yang ***@***.***>日期： 2024年1月12日周五 09:59收件人： xihongyang1999/CCGC ***@***.***>抄送： TengXYi ***@***.***>, Author ***@***.***>主    题： Re: [xihongyang1999/CCGC] X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？ (Issue #5)
Closed #5 as completed.

**Comment by xihongyang1999** [comment]
您好，我做的聚类任务是直接全数据集进行测试的，没有进行划分，因为都是在无监督场景下进行的。所以对整个数据集进行了聚类性能测试

**Comment by TengXYi** [comment]
感谢回复，请问你们课题组是做图聚类任务的吗，想问一下还有必要对除了 cora,citeseer,pubmed 这三个数据集以外的数据集做划分吗？发自我的手机-------- 原始邮件 --------发件人： Xihong Yang ***@***.***>日期： 2024年1月24日周三 09:54收件人： xihongyang1999/CCGC ***@***.***>抄送： TengXYi ***@***.***>, Author ***@***.***>主    题： Re: [xihongyang1999/CCGC] X这个属性矩阵是节点特征还是既包含节点特征又包含图结构信息啊？ (Issue #5)
您好，我做的聚类任务是直接全数据集进行测试的，没有进行划分，因为都是在无监督场景下进行的。所以对整个数据集进行了聚类性能测试
