### ISSUE TITLE
关于损失函数与聚类准确度的关系

### ISSUE THREAD

**Issue by LiXue78** [xihongyang1999/CCGC#6]
您好，我有个问题想向您请教一下。
关于节点聚类问题，在训练过程中，本文设计的损失函数是不断降低的，但是聚类的准确度是不断波动的（并没有从整体上呈现出逐步上升的趋势），我们选取最好的一次作为最终的聚类效果。请问为什么是这样的呢？

**Comment by xihongyang1999** [comment]
你好，follow之前的经典聚类算法，我们也选用kmeans作为本文聚类的方法，其中每次进行kmeans的时候都会进行随机初始化，因此这可能是导致准确度不断波动的原因。至于选择best的处理方式也是follow其他的经典聚类方法，例如DCRN、DFCN、SDCN等，CCGC的设置与其他论文相同。

**Comment by LiXue78** [comment]
您的回答对我很有帮助，非常感谢您的解答。
